sudo: required
services: 
  - docker
env:
  global: 
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_PYTHON=3.8
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - if [ ! -d $HOME/google-cloud-sdk/bin ]; then
    rm -rf $HOME/google-cloud-sdk;
    curl https://dl.google.com/dl/cloudsdk/channels/rapid/install_google_cloud_sdk.bash| bash > /dev/null;
  fi
  - source $HOME/google-cloud-sdk/path.bash.inc

    